services:
  debezium:
    image: debezium/connect:2.7.3.Final
    environment:
      BOOTSTRAP_SERVERS: 172.17.0.1:2255
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_status
    ports:
      - 8083:8083