services:
  postgres:
    image: postgres:latest
    ports:
      - 4432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=debezium_master
    volumes:
      - /var/lib/pgsql/debezium_pg_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    hostname: broker
    ports:
      - "2255:2255"
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://172.17.0.1:2255,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:2255,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG_RETENTION_HOURS: 168        # 1 week (or more)
      KAFKA_LOG_RETENTION_BYTES: -1         # No size limit
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true # If you're not manually creating them
    volumes:
      - kafka-data:/kafka/data

  debezium:
    image: debezium/connect:2.7.3.Final
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: 172.17.0.1:2255
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      OFFSET_FLUSH_INTERVAL_MS: 10000
      ENABLE_APICURIO_CONVERTERS: "false"
    volumes:
      - connect-data:/kafka/connect
    ports:
      - 8083:8083

volumes:
  kafka-data:
    driver: local
  connect-data:
    driver: local
